### ISSUE TITLE
Signup & Signin | Loader not visible when button is clicked

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#1]
Scenario:
When user clicks on signup or sign in button, following issues are visible

1. No loader shown, user is unsure if app is performing any action
2. No alert shown in case of failure. User needs to be notified with what went wrong so that they can take corrective actions.

**Comment by dastonrajapboyev** [comment]
i want to help with that problem and will try

**Comment by aadeshkulkarni** [comment]
Sure, please go ahead. 

This is fixed using react-toastify. 👇🏻

> 2. No alert shown in case of failure. User needs to be notified with what went wrong so that they can take corrective actions.

You can pick up this

> 1. No loader shown, user is unsure if app is performing any action

**Comment by dastonrajapboyev** [comment]
i have fixed this you can see and tell me how

**Comment by dastonrajapboyev** [comment]
i opened new branch snipper

**Comment by aadeshkulkarni** [comment]
@dastonrajapboyev - Please create a pull request of your feature branch with master branch and mention the issue in the PR.

**Comment by dastonrajapboyev** [comment]
> @dastonrajapboyev - Please create a pull request of your feature branch with master branch and mention the issue in the PR.

i have create pull request you can check i'm sorryb this is my first time contributing

**Comment by aadeshkulkarni** [comment]
@dastonrajapboyev - There are merge conflicts in your new PR as well. Please resolve the merge conflicts at the earliest so that this can be closed.

And please refrain from creating duplicate PRs for the same issue # in future.

**Comment by aadeshkulkarni** [comment]
Fixed  & closed with this [commit](https://github.com/aadeshkulkarni/medium-app/commit/2842f8675a897b318475672db3000c312bff7d01)
