### ISSUE TITLE
Feature | Profile page for user

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#10]
Build a profile page like this

<img width="1790" alt="Screenshot 2024-04-27 at 8 05 24 AM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/8b2219ba-4160-469c-abef-db9ee03be48e">

The profile should be accessible from the url like this

`xyz.com/@username`

Features:
- User posts
- User personal information (edit option)

Following and Followers is out of scope of this PR and can be ignored for now.

**Comment by jyo142** [comment]
hey @aadeshkulkarni can i try tackling this?
