### ISSUE TITLE
Feature | Implement Subscriber

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#100]
### What ?
- Users should be able to able to follow one another. 
- Users should be able to able to unfollow one another. 

### How ?
This is my approach (feel free to add your inputs to make it better)
- Create a new table/schema = Subscriber (with id, userId, subscriberId, creationDate as columns)
- Create a new subscriberRouter with the following endpoints
        - POST api/v1/subscriber/subscribe  (userId, subscriberId => Subscribe Endpoint
        - POST api/v1/subscriber/unsubscribe (userId, subscriberId) => Unsubscribe Endpoint
        - GET api/v1/subscriber/:userId => List of subscribers for a user

This ticket is specific to backend ONLY.

Refer [this](https://stackoverflow.com/questions/4895809/database-design-for-followers-and-followings)

**Comment by vlokesh08** [comment]
Hi @aadeshkulkarni can you please assign this to me!

**Comment by aadeshkulkarni** [comment]
Sure
