### ISSUE TITLE
Bug | Blogs UI Inconsistency for Mobile screens

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#101]
### When ?
- User opens /blogs route on mobile screen

### What ?
- Some blogs (that have less content) don't take the full width of the screen.

### Expectation:
- All blogs should take full width on mobile screens.

### Screenshot
![Screenshot 2024-05-25 at 12 02 11 AM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/9a28eccc-71f1-4544-8d18-5d4c04358487)

**Comment by Gouravgarg02** [comment]
Is it solved?

**Comment by Gourav094** [comment]
Can you please assign this to me?

**Comment by aadeshkulkarni** [comment]
> Can you please assign this to me?

At the moment, #126 is assigned to you. Once your PR get's merged & no one else has requested for this until then, I'll assign this to you.

**Comment by Gourav094** [comment]
PR for #126 is merged. Can you assign this to me?

**Comment by aadeshkulkarni** [comment]
Done. 
Please ensure you don't change the larger screen styling while fixing this.
