### ISSUE TITLE
Bug | Invalid redirect on Publish button click

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#102]
### When ?
- User opens the write page
- Keeps title & content empty 
- Clicks on the publish button

### What ?
- The publish button should be disabled if title & content empty
- The publish button should not open the topics dialog if title & content is empty

### Screenshot

![Screenshot 2024-05-25 at 1 48 18 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/494e999b-05bc-46f2-a5b3-5dae3c3fa0ac)

**Comment by dhairya-create** [comment]
Hi @aadeshkulkarni can you assign this?

**Comment by dhairya-create** [comment]
Sure, buddy! I'll dig into some another issue

**Comment by karanpatel1993** [comment]
Created a PR for this. https://github.com/aadeshkulkarni/medium-app/pull/105

**Comment by aadeshkulkarni** [comment]
Congrats!

**Comment by karanpatel1993** [comment]
First open source contribution :)
