### ISSUE TITLE
Feature | Add more formatting options to the Editor

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#103]
### Where ?
- User signs in 
- User clicks on write
- User starts typing, selects a text

### What ?
At the moment, there are limited formatting options. (see screenshot)

### Expectation
Add more standard formatting options
- code
- Numbered List / Unordered List / Tasklist

### Screenshot

![Screenshot 2024-05-25 at 1 53 29 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/c1bdb217-b6d7-48d1-8727-71d735f177db)

**Comment by dhairya-create** [comment]
Hi @aadeshkulkarni Can you assign this ?

**Comment by aadeshkulkarni** [comment]
Sure, done
