### ISSUE TITLE
Bug | Topic dropdown does not close when clicked outside

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#106]
### Where? 
- User signs in
- User clicks on Write button
- User enters dummy title and content
- User clicks on publish button
- User opens the Topics dropdown. 
- User tries to close to Topic dropdown without selecting any value.

### What ?
Once a dropdown is opened, it cannot be closed until user selects a value.

### Expectation
User should be allowed to close the dropdown without selecting value.

**Comment by swastik4805** [comment]
Could you assign the issue to me?

**Comment by aadeshkulkarni** [comment]
Sure
