### ISSUE TITLE
Enhancement | Allow Embedding of Youtube videos within the Quill Editor

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#107]
### Where?
- Write page
- Edit page

### What ?
Users should be able embed any youtube video on their blog

### References:
- [Quill.js and custom prompt for video handler](https://stackoverflow.com/questions/67901856/quill-js-and-custom-prompt-for-video-handler)

**Comment by dhairya-create** [comment]
Hi @aadeshkulkarni, I'd like to work on this issue. Could you please assign it to me?
I have worked on React Quill on one of the bugs already.

**Comment by aadeshkulkarni** [comment]
Sure, done

**Comment by dhairya-create** [comment]
![image](https://github.com/aadeshkulkarni/medium-app/assets/74588712/49ec7955-e45a-4743-8ca1-f33d07e81010)


In the Quill when users clicks on the button
A prompt will come for the user to enter the Youtube link

After pressing Enter
Embedded Youtube video will be shown
