### ISSUE TITLE
Enhancement | Implement Subscriber on Profile page

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#120]
dependent on completion of backend issue #100 
<hr />

### Where ?
- User visits a blog
- User clicks on the Author
- User sees the profile page of Author

### What ?
- User should be able Follow/ Unfollow the Author
- User should be able to see how many followers the Author has
- User should be able to see who the Author is following

### Screenshot: (Desktop)

![Screenshot 2024-05-30 at 11 31 21 AM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/b65a2879-5e22-4927-ac2d-44f1231a5cb5)

### Screenshot: (Mobile)

![Screenshot 2024-05-30 at 11 31 05 AM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/b0aa8f78-5cec-4d45-ba31-4c36c514d374)

### Insights:

- POST api/v1/subscriber/subscribe (userId, subscriberId => Subscribe Endpoint
- POST api/v1/subscriber/unsubscribe (userId, subscriberId) => Unsubscribe Endpoint
- GET api/v1/subscriber/:userId => List of subscribers for a user

Please attach screenshots / recordings to the PR

**Comment by HarshS1611** [comment]
I would love to work on this feature. Here is how I will do this task:

1. I will create a button in the `frontend/src/components/User/UserProfile.tsx` file named `Follow` .
2. I will apply a `useState` hook to toggle between `follow` and `unfollow` .
3. Then I'll create a hook in `hooks/user.ts` to subscribe` , `unsubscribe`, and `fetch subscribers` from DB.
4. The authorId is already present as the props and the `subscriberId` can be fetched from `localStorage` .
5. After that, I'll integrate to the front end - all subscribers, follow, unfollow.

**Comment by aadeshkulkarni** [comment]
Sure, assigning it to you.

**Comment by HarshS1611** [comment]
I have added the screenshots of my work. Let me know your thoughts.

![image](https://github.com/aadeshkulkarni/medium-app/assets/81004813/d8ef840c-487f-4f18-b0f7-280420fa1f70)

![image](https://github.com/aadeshkulkarni/medium-app/assets/81004813/6616f4cf-c8d9-40db-a6ae-2090d18bb4bc)

![image](https://github.com/aadeshkulkarni/medium-app/assets/81004813/19d82709-e03e-4464-bb04-10827a6f2f55)

![image](https://github.com/aadeshkulkarni/medium-app/assets/81004813/a9e75aa6-626d-41a2-99ab-6a6b62eb4371)

![image](https://github.com/aadeshkulkarni/medium-app/assets/81004813/d2d4e2e8-1c00-4aa8-8fb5-cb967a1a2816)

Also, users cannot see the follow button on their profile page.
![image](https://github.com/aadeshkulkarni/medium-app/assets/81004813/c521d588-932c-4afd-a37b-8f4386145730)
