### ISSUE TITLE
Enhancement | Auto-save indicator

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#123]
### Where ?
- User signs in
- User clicks on Write
- User starts writing

### What ?
- User's changes are autosaved at regular interval to the Local storage (this is already implemented)
- User should be notified that their changes are autosaved. ( this needs to be implemented)

### More details:
- Notification should be within the page, not as a dialog / modal
- Notification should not shift layout of the screen

**Comment by Kunall-singh** [comment]
can you please assign this issue to me?

**Comment by aadeshkulkarni** [comment]
> can you please assign this issue to me?

Krupa is driving this feature.
@KrupaPanchal2527  - What are your thoughts on this ? Would it be okay for Kunal to pick it up ?

**Comment by KrupaPanchal2527** [comment]
@aadeshkulkarni sure please assign it to him.

**Comment by Kunall-singh** [comment]
Thank you @KrupaPanchal2527.
@aadeshkulkarni  Currently, the draft saves every 15 seconds, but the notification reappears even when no changes are made to the draft. Should it continue to notify after every 15 seconds even if there are no modifications? Please let me know. Below is a video of the pop up appearance. please let me know if anything else needed

https://github.com/aadeshkulkarni/medium-app/assets/107796595/08882a83-f30b-4fe7-aee3-8c4e8b259788

**Comment by aadeshkulkarni** [comment]
> * Notification should be within the page, not as a dialog / modal

Notification should be within the page, not as a dialog / modal

Something like this:

<img width="1134" alt="Screenshot 2024-06-04 at 7 49 54 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/9ed1515a-099b-4465-884c-9aa9ef03c50e">

Reference: Medium's write page.

**Comment by Kunall-singh** [comment]
@aadeshkulkarni Apologies for my misunderstanding. So far i have able to reach this point, actually i am not sure about the design or where the text should be. i have added two screenshots below showing the progress so far. please let me know if any kind of changes needed. 
Also i was thinking that after the autosave happens should just "Saved" appears or "Last saved at {time when draft saved}" should appear?
![Screenshot 2024-06-04 112302](https://github.com/aadeshkulkarni/medium-app/assets/107796595/1bfd51df-4477-4d5c-8000-e11bd3a6ea14)
![Screenshot 2024-06-04 112332](https://github.com/aadeshkulkarni/medium-app/assets/107796595/92e7611d-c851-41ff-a185-383876493caa)

**Comment by aadeshkulkarni** [comment]
Just 'saved' should be fine.

Ensure the following:
- When the `Draft in Kunal Singh * Saved` container becomes visible on the screen, there shouldn't a layout shift of the content that is below it.
- The spacing between "Draft in" and "Kunal Singh" seems off
- The font-weight/boldness of Draft in Kunal Singh seems off.
