### ISSUE TITLE
Bug | Edit Blog | Title & Content missing

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#130]
### Where ?
- User signs in
- User writes a blog & publishes it
- User opens the blog & clicks on edit
- Edit page opens

### What ?
- The title & content are empty (without content) within the edit page. Ideally, it should be displayed.

**Comment by Gourav094** [comment]
Can you share a picture of the issue?
![image](https://github.com/aadeshkulkarni/medium-app/assets/97150553/25979704-04a4-4248-8696-35cc8afec998)

**Comment by Gourav094** [comment]
@aadeshkulkarni  I think there is one more bug. We can clap multiple times on a post but we should be able to clap once on a post
