### ISSUE TITLE
Enhancement | Add creationDate to User table

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#131]
### Where ?
Postgres - User table

### What ?
Add a new CreationDate with default value = currentdatetime

### Reference 
creationdate field for Post table

**Comment by HarshS1611** [comment]
I can work on it. Here is how I will tackle this problem : 

1. I will add a new attribute `CreationDate` in the `User` table in `prisma/schema.prisma` file .
2. Then I will set its value `DateTime @default(now())`.
3. I will run the command `npx prisma migrate dev --name added_creationDate_to_users`.
4. After migration, I'll run `npx prisma generate --no-engine`.

**Comment by aadeshkulkarni** [comment]
Alright, Assigned to you.

**Comment by HarshS1611** [comment]
I have made the required changes and created PR #149 . Could you review it and let me know your thoughts?
