### ISSUE TITLE
Feature | Implement Comments

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#132]
A user can comment on Post. 
A user can comment on a comment within a post. (Maximum 2 levels only).

Since Comment-to-Post is a 1:M relationship, we need to map postId to a comment record.

- Build a new schema for Comments
-  Build a new router for Comments
- Expose CRUD for comments.

Please share your approach before requesting for assignment.

**Comment by Kunall-singh** [comment]
@aadeshkulkarni Here is my approach to this issue:

As I can see in the Prisma schema, a "Comment" table is present, but a few more columns are needed. These columns are:

message
createdAt
updatedAt
user (to get the username while rendering)
post (Blog)
postID (Id)
parent
children
parentID
The parent will be the top comment of a nested comment, whereas children will be the nested comments or the replies to the parent comments. The parentID will be used to determine the main comment in a nested comment.

Additionally to achieve the 1:M relation between (user and comments) and (posts and comments), in the User table, a comments column will be created with the previously created table Comment[]. The same will be done in the Post table.

After that, new API endpoints will be created, such as:

/:Id/comments

Here, four operations will be implemented: Create, Update(with the help of commentID), Delete(with the help of commentID), and Get comments. When creating comments, with the help of parentID and children, a maximum of two levels can be achieved.

Please let me know if this implementation is acceptable. I would love to work on it.

**Comment by Kunall-singh** [comment]
@aadeshkulkarni Hello, I am trying to setup the backend locally. I have tried to follow every step and put all the required things accordingly, but i think i am missing something. attaching some screenshots can you please help me out if possible. also i have already done the db migrations.
![Screenshot 2024-06-06 091707](https://github.com/aadeshkulkarni/medium-app/assets/107796595/58bcc97c-7ed1-447e-adc7-abbc92236d14)
![Screenshot 2024-06-06 092634](https://github.com/aadeshkulkarni/medium-app/assets/107796595/d11dc057-7722-4a2b-b951-0eacd0842efe)
![Screenshot 2024-06-06 092705](https://github.com/aadeshkulkarni/medium-app/assets/107796595/f67548dd-14e3-4846-9d5b-0f2a778eeeda)
![Screenshot 2024-06-06 092715](https://github.com/aadeshkulkarni/medium-app/assets/107796595/ab227e1a-67eb-452d-9d13-730dc2caf62c)

**Comment by Kunall-singh** [comment]
@aadeshkulkarni Thank you for the assist. Is this issue still open or taken?
