### ISSUE TITLE
Bug | Signup | Incorrect notification message

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#143]
If user enters email that already exists in the system, an incorrect notification is displayed. The error message that is sent by the backend should be shown instead.

![Screenshot 2024-06-07 at 3 09 11 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/8a211292-0ea6-4fec-a66d-978f37ee5e6a)

**Comment by parthzile** [comment]
### Proposed Solution
Capture Backend Error Message:

> Ensure that the frontend is correctly capturing the error message sent by the backend.
> Display Error Message:
> Display the captured error message in the notification area.
> Implementation Steps

Update API Call Handling:
> Modify the API call handling to capture the error response correctly.

Display the Error Message:

> Use the captured error message to update the notification displayed to the user.

**Comment by Robot-dev11** [comment]
Can i work on it?
