### ISSUE TITLE
Bug | Profile > Home | Whitescreen

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#144]
### Where ?
- User signs up
- User goes to profile page
- Since user has written any article yet, a white screen is displayed.

### What ?
- Instead of showing the white screen, inform the user that they have not done any activity. And also display a `write` blog button.

### Screenshot

![Screenshot 2024-06-07 at 3 12 17 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/758109bc-9405-4c2b-8f91-6f51f165e51f)

**Comment by Jaishree2310** [comment]
Hi @aadeshkulkarni, I am interested in solving this.. can you please assign this token to me? 
Thanks!

**Comment by aadeshkulkarni** [comment]
Sure
