### ISSUE TITLE
Bug | Avatar | Color contrast 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#146]
### Issue:
When user hovers over an Avatar icon, the bg-text colour contrast is janky.

### Solution:
Change the hover colors:
The new combination of bg & text color should pass this test.
https://webaim.org/resources/contrastchecker/

![Screenshot 2024-06-07 at 3 16 03 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/dc9d0dd1-c218-4fed-a285-e601a6e0e182)

**Comment by vverma022** [comment]
I'd like to work on this issue
