### ISSUE TITLE
Bug | Navigation | not navigating to other user's page from one users page even after clicking.

### ISSUE THREAD

**Issue by M0hitReddy** [aadeshkulkarni/medium-app#152]
current behaviour :
 In home page, when searching for a userand clicked on that user its opening that users page for once. If i search for other user on the previous users page and click on it its not navigating to the 2nd users page. it is remaining on same page.But the url is changing when clicked on other user.
expected : 
While we are on a users page, if we search for other user in search field on top, it should navigate to that users page.

1.
![Screenshot 2024-06-07 233719](https://github.com/aadeshkulkarni/medium-app/assets/114643178/567de40e-208a-42a4-97d2-f274609b9ba9)
2.
![Screenshot 2024-06-07 233731](https://github.com/aadeshkulkarni/medium-app/assets/114643178/d29a263c-4819-4108-ae22-a3bfbeab80e2)
3.
![Screenshot 2024-06-07 233742](https://github.com/aadeshkulkarni/medium-app/assets/114643178/b956d0bd-3399-46d2-b316-c506044d2aff)
4.
![Screenshot 2024-06-07 233757](https://github.com/aadeshkulkarni/medium-app/assets/114643178/b983e4ae-7143-4ed3-af5b-ec9688b7b050)

**Comment by aadeshkulkarni** [comment]
I have checked and confirm that this is a bug.

**Comment by M0hitReddy** [comment]
can you assign me this.

**Comment by Prithvi-R** [comment]
if its not fixed yet assign me
