### ISSUE TITLE
Bug | Bookmarks page wrong navigation

### ISSUE THREAD

**Issue by M0hitReddy** [aadeshkulkarni/medium-app#153]
In bookmarks page there is a text "No bookmarks yet! You can bookmark blogs in the blogs page [here](https://medium-app-zeta.vercel.app/signin)". where "here" is a link and on clicking it its navigating to signin page even we are logged in.
1.
![Screenshot 2024-06-07 233858](https://github.com/aadeshkulkarni/medium-app/assets/114643178/e016972c-697c-434f-960b-2ffac55abd07)

**Comment by AtharvaChobe** [comment]
retrieve the user details from local storage and we can use this method to resolve this issue.

**Comment by M0hitReddy** [comment]
> retrieve the user details from local storage and we can use this method to resolve this issue.

why not from database?

**Comment by AtharvaChobe** [comment]
> > retrieve the user details from local storage and we can use this method to resolve this issue.
> 
> why not from database?

It's not needed because when the user is logged in the user data is stored in local storage(in reference to the code). just check whether the user data is in the local storage, if it is it means that user if logged in and replace the link to "/blogs" instead of "/signin"

**Comment by aadeshkulkarni** [comment]
Localstorage should be fine. Anyone interested in picking this up and closing it swiftly?

**Comment by AtharvaChobe** [comment]
Yes i can work on this

**Comment by aadeshkulkarni** [comment]
Alright. Issue assigned.
