### ISSUE TITLE
Implement Bookmark feature

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#16]
When?
- User is reading an article.

What?
- User should be able to bookmark (Save for later) the article.
- User should be able to view the bookmarked articles by clicking on the user avatar > bookmarks

**Comment by jyo142** [comment]
@aadeshkulkarni may I work on this feature as well?

**Comment by aadeshkulkarni** [comment]
Sure. 
Please share your approach to implement this feature before starting dev

**Comment by jyo142** [comment]
As the ticket mentioned will be creating a page to see "Bookmarked Pages" in the user avatar dropdown.
- In every article I will add an option to "bookmark" maybe adding a star icon by the title
<img width="1470" alt="Screenshot 2024-05-02 at 11 39 41 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/4103523/5cfc9fd5-56c6-48b1-bde0-46447eb09525">

Then in the list you should be able to see which articles you have bookmarked with a star icon
<img width="801" alt="Screenshot 2024-05-02 at 11 41 28 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/4103523/c4be2d1f-6782-4023-a172-b4e753b219d2">


On the backend
- would create a UserBookmarkToPost table which would have a mapping of which user by id bookmarked which post by id

**Comment by aadeshkulkarni** [comment]
Alright. Sounds good.

2 Suggestions: 
- Naming the table `Bookmark` would suffice, instead of `UserBookmarkToPost`.
- Use a Bookmark Icon instead of Star Icon (Similar to how Medium does it) [You can use https://heroicons.com/ since it's actively supported by the Tailwind community]

**Comment by aadeshkulkarni** [comment]
@jyo142 - Good work! The feature is now live. 

I've tested it and adding few minor bugs as new issues.

**Comment by jyo142** [comment]
@aadeshkulkarni got it! will take that bug
