### ISSUE TITLE
Bug | LoggedIn User does not see correct Follower count

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#168]
### Logged In as Aadesh (Shows 0 Followers, this is incorrect)
![Screenshot 2024-06-13 at 12 07 13 AM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/79c7cd7f-4e5c-477e-82d3-e34d321c3b4d)

### Logged in as different User (Shows 4 Followers, this is correct)

![Screenshot 2024-06-13 at 12 09 51 AM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/4ef7ccb5-2d58-4f7d-99e0-3bdad556ff4d)

**Comment by Prithvi-R** [comment]
can you assign me this issue?

**Comment by aadeshkulkarni** [comment]
Sure, assigned it to you.

**Comment by Prithvi-R** [comment]
> Sure, assigned it to you.

Pull Request made kindly check it.

**Comment by codeseker** [comment]
Can you please merge My PR Request too.
