### ISSUE TITLE
Homepage | Add a sign in button on the Appbar 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#18]
**Issue:**
Currently, In-order to login, The user needs to make the following hops to reach the Sign in page:

- Go to homepage, click on Start reading button (Redirects to signup page, if user is not logged in)
- Go to Signup page, click on login anchor tag (Redirects to signin page)
And now the user is finally able to see the Sign in screen 

**Expectations:**
When user visits the app,
If user NOT loggedIn, then show a `Sign In` link on the Appbar which re-directs to sign in page.
If user logged, then don't show the `Sign in` link on the Appbar

<img width="1794" alt="Screenshot 2024-05-03 at 12 24 04 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/b79a71c0-d008-4a65-a385-a265d7d73435">

**Comment by vijaynvvr** [comment]
Hey, may I work on this issue? Could you please assign me to this issue?

**Comment by aadeshkulkarni** [comment]
Done.
Please fork the code, create a feature branch and raise the PR.
Ensure that you link this issue to your PR.

**Comment by vijaynvvr** [comment]
Done!
Could you please review it
