### ISSUE TITLE
Bug | Additional width on Landing page

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#180]
### Where ?
- Landing page https://figuringout.life

### What ?
- On large screens, the width should be equal to viewport width. But, it is currently exceeding the viewport width. As a result a horizontal scrollbar is visible, which shouldn't be visible.

![Screenshot 2024-06-15 at 8 15 53 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/39317718-eb3d-48cd-a8a7-ba8bada2dbfe)

**Comment by dhairya-create** [comment]
**Proposed Solution:**

Resolved issue of horizontal scrollbar on large screens by ensuring the html and body elements adhere to viewport width (width: 100vw;) and hide horizontal overflow (overflow-x: hidden;). Adjusted media query to limit scrolling to vertical (overflow-y: scroll;) on small screens, preventing unintended horizontal scrolling.



`
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wdth,wght@0,62.5..100,100..900;1,62.5..100,100..900&display=swap');

@tailwind base;

@media screen and (max-width: 768px) {
  @layer base {
    html {
      scroll-snap-type: y mandatory;
    }
    body {
      overflow-y: scroll; 
      scroll-snap-type: y mandatory;
    }
    .snap-center {
      scroll-snap-align: center;
    }
  }
}

@tailwind components;
@tailwind utilities;

@layer base {
  html, body {
    width: 100vw; 
    overflow-x: hidden; 
    font-family: 'Noto Sans', sans-serif;
    box-sizing: border-box;
  }

  /* Keep adding variants for button here */
  button.primary {
    @apply block text-white bg-green-700 text-sm rounded-3xl px-4 py-2 m-0 hover:bg-green-800;
  }

  button.primary:disabled {
    @apply opacity-60 pointer-events-none;
  }

  button.secondary {
    @apply block bg-white text-sm rounded-3xl px-4 py-2 m-0 hover:bg-gray-200 border;
  }

  button.secondary:disabled {
    @apply opacity-60 pointer-events-none;
  }
}

.ql-editor {
  @apply font-noto-serif text-lg !p-0 md:p-4;
}

.ql-editor.ql-blank::before {
  @apply inset-0 not-italic text-gray-400 font-light text-xl;
}

.quill {
  min-height: 500px;
}

.blog-card .quill {
  min-height: 50px;
}

.blog-card .ql-editor {
  padding: 0;
}

.blog-card .ql-editor p,
.blog-card .ql-editor h1,
.blog-card .ql-editor h2,
.blog-card .ql-editor h3 {
  @apply text-sm;
}

.sparkle {
  width: 5px;
  height: 5px;
  position: absolute;
  border-radius: 50%;
  opacity: 0;
  animation: sparkle-animation 0.5s forwards;
}

.star {
  width: 0;
  height: 0;
  border-left: 3px solid transparent;
  border-right: 3px solid transparent;
  border-bottom: 5px solid;
}

@keyframes sparkle-animation {
  0% {
    opacity: 1;
    transform: scale(0);
  }
  100% {
    opacity: 0;
    transform: scale(1.5);
  }
}

.clap-button {
  display: inline-flex;
  align-items: center;
  cursor: pointer;
  transition: transform 0.3s ease-in-out;
}

.clapping {
  transform: scale(1.5);
}

.container-chevron {
  position: relative;
  width: 24px;
  height: 24px;
}

.chevron {
  position: absolute;
  width: 28px;
  height: 2px;
  opacity: 0;
  transform: scale3d(0.5, 0.5, 0.5);
  animation: move 3s ease-out infinite;
}

.chevron:first-child {
  animation: move 3s ease-out 1s infinite;
}

.chevron:nth-child(2) {
  animation: move 3s ease-out 2s infinite;
}

.chevron:before,
.chevron:after {
  content: ' ';
  position: absolute;
  top: 0;
  height: 100%;
  width: 51%;
  background: #fff;
}

.chevron:before {
  left: 0;
  transform: skew(0deg, 30deg);
}

.chevron:after {
  right: 0;
  width: 50%;
  transform: skew(0deg, -30deg);
}

@keyframes move {
  25% {
    opacity: 1;
  }
  33% {
    opacity: 1;
    transform: translateY(30px);
  }
  67% {
    opacity: 1;
    transform: translateY(40px);
  }
  100% {
    opacity: 0;
    transform: translateY(55px) scale3d(0.5, 0.5, 0.5);
  }
}

.text {
  display: block;
  margin-top: 75px;
  margin-left: -30px;
  font-family: 'Helvetica Neue', 'Helvetica', Arial, sans-serif;
  font-size: 12px;
  color: #fff;
  text-transform: uppercase;
  white-space: nowrap;
  opacity: 0.25;
  animation: pulse 2s linear alternate infinite;
}

@keyframes pulse {
  to {
    opacity: 1;
  }
}


`

**Comment by aadeshkulkarni** [comment]
Alright. Please raise a PR

**Comment by aadeshkulkarni** [comment]
Thank you for the contribution!
