### ISSUE TITLE
Bug | Blog | Mobile Screen ONLY

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#183]
### Current

![Screenshot 2024-06-15 at 8 36 40 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/ad6470be-fb58-4761-bd5d-513c5dc37ce5)

### Expectation

![Screenshot 2024-06-15 at 8 38 21 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/2ea056a7-204e-4e20-9475-2d53a470fcb2)

**Comment by sameer-soni** [comment]
@aadeshkulkarni hey, can i work on this?

**Comment by aadeshkulkarni** [comment]
Sure, assigned to you.

**Comment by sameer-soni** [comment]
@aadeshkulkarni done.

**Comment by aadeshkulkarni** [comment]
Thank you for the contribution!
