### ISSUE TITLE
Bug | Header issue on iPhone SE / OnePlus 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#184]
### Screenshot 
![Screenshot 2024-06-15 at 8 41 09 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/44fe26cb-1b62-44d9-bd5e-95ec0d19a724)

**Comment by dhairya-create** [comment]
![image](https://github.com/aadeshkulkarni/medium-app/assets/74588712/29e7b4b8-b000-4f6f-955f-db6899f7543a)


- Flexbox's help made both the buttons (Signup and SignIn) responsive.
-  Added whitespace-nowrap to prevent text from wrapping within an element button

**Comment by aadeshkulkarni** [comment]
Looks good. please raise a PR

**Comment by aadeshkulkarni** [comment]
Thank you for the contribution
