### ISSUE TITLE
Fix | React-toast container width

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#19]
If screen = mobile, 
Notification width = screen width ✅ (this already works in most cases)
 
If screen > mobile [i.e. Tablet, desktop, ...], 
Notification width = ~500px ❌ 

**Reasoning:** 
The notification content should be displayed on 1 line ideally if character count is <= ~50 characters.
If notification character-count increases 50, wrap the content to next line.

The below notification content should have been displayed in 1 line.
<img width="1794" alt="Screenshot 2024-05-03 at 12 21 57 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/0c58774d-c6b1-44ba-ae20-a4f97ee4ed46">

**Comment by RahulSingh9131** [comment]
Assing this issue to me, I am interested in fixing this issue.

**Comment by aadeshkulkarni** [comment]
Sure, please fork the repository, create a branch from master, and raise a PR. 
Ensure that you're linking this issue to your PR description.

**Comment by RahulSingh9131** [comment]
hey i have fixed this issue , check the PR
