### ISSUE TITLE
Enhancement | Add CSS Skeleton | Shimmer

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#20]
Add Shimmer loading to following pages until data is painted:

- /blogs
- /blog

Reference article- https://flowbite.com/docs/components/skeleton/

Please create a src/skeletons/ directory under which all skeletons are created.

PS: Use tailwind, refrain from installing additional NPM libraries. We don't want to unnecessarily increase bundle size.

**Comment by RahulSingh9131** [comment]
Hey, assign this issue to me. I am familiar with the tech stacks used in this project

**Comment by RahulSingh9131** [comment]
Check This PR and let me know if we need any changes in the PR.

**Comment by aadeshkulkarni** [comment]
@RahulSingh9131 - Good work. Your PR is merged. But, shimmer for the /blog page is missing. so keeping this issue open.

**Comment by RahulSingh9131** [comment]
@aadeshkulkarni   On local i can't see any data being rendered on blog page . is there any bug here?

<img width="1440" alt="Screenshot 2024-05-10 at 5 26 27 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/87935709/9932924b-d844-4bd8-aa26-8e8712c1be40">

**Comment by aadeshkulkarni** [comment]
> @aadeshkulkarni On local i can't see any data being rendered on blog page . is there any bug here?
> 
> <img alt="Screenshot 2024-05-10 at 5 26 27 PM" width="1440" src="https://private-user-images.githubusercontent.com/87935709/329570070-9932924b-d844-4bd8-aa26-8e8712c1be40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDI5NDAsIm5iZiI6MTcxNTM0MjY0MCwicGF0aCI6Ii84NzkzNTcwOS8zMjk1NzAwNzAtOTkzMjkyNGItZDg0NC00YmQ4LWFhMjYtOGU4NzEyYzFiZTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDEyMDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTY0OGJkMTBiNGZkNmM3Yzc4MTY2MTFiYjdiY2M0YTVjZGIxNjExNjE1Y2Y0ZmJlYTJkNjZjZTczZGZjZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lh-Xa3bty9kjup0uD_ZQEmos61EPrW307oiajyWCwpc">

Should work fine on local. 

Any errors on console / network tab ?

**Comment by RahulSingh9131** [comment]
> > @aadeshkulkarni On local i can't see any data being rendered on blog page . is there any bug here?
> > <img alt="Screenshot 2024-05-10 at 5 26 27 PM" width="1440" src="https://private-user-images.githubusercontent.com/87935709/329570070-9932924b-d844-4bd8-aa26-8e8712c1be40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDI5NDAsIm5iZiI6MTcxNTM0MjY0MCwicGF0aCI6Ii84NzkzNTcwOS8zMjk1NzAwNzAtOTkzMjkyNGItZDg0NC00YmQ4LWFhMjYtOGU4NzEyYzFiZTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDEyMDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTY0OGJkMTBiNGZkNmM3Yzc4MTY2MTFiYjdiY2M0YTVjZGIxNjExNjE1Y2Y0ZmJlYTJkNjZjZTczZGZjZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lh-Xa3bty9kjup0uD_ZQEmos61EPrW307oiajyWCwpc">
> 
> Should work fine on local.
> 
> Any errors on console / network tab ?


Yes the error is in ActionBox component, i am getting undefined user , since in my localStorage user key is undefined.
<img width="1440" alt="Screenshot 2024-05-10 at 5 46 10 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/87935709/57d27d7e-3ea1-4580-bac6-cf42522f2634">
<img width="1440" alt="Screenshot 2024-05-10 at 5 47 25 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/87935709/c82fdf48-7c0b-4408-a0f2-3b3b797d96d5">

**Comment by aadeshkulkarni** [comment]
Ideally, the app should've redirected to login screen. I'll create a new issue for this.
You can clear your localstorage and work for now

**Comment by RahulSingh9131** [comment]
ok sure

**Comment by RahulSingh9131** [comment]
@aadeshkulkarni have pushed the remaining changes of skeleton in this PR, have a look
