### ISSUE TITLE
Enhancement | Enhance Password Input Visibility and Error Handling in Sign-In and Sign-Up Processes

### ISSUE THREAD

**Issue by minhajul-im** [aadeshkulkarni/medium-app#21]
Currently, the sign-in and sign-up processes in our application lack adequate feedback for password input, leading to usability and security concerns. Here are the main issues identified:

Password Visibility: The password input field does not provide visual feedback to users, making it difficult for them to verify their input. This poses a usability challenge, especially when typing complex passwords.

Mistake Recognition: Users are unable to identify if they've made a mistake while entering their password since the characters are not visible. This lack of feedback increases the likelihood of input errors and frustration.

Error Handling: In case of a password mistake, the system fails to provide any error message or indication, leaving users unaware of the issue.

Proposed Solution:
To address these issues, we propose the following enhancements:

Toggle Password Visibility: Implement a feature that allows users to toggle password visibility, displaying the characters as dots or revealing them when needed. This will enable users to verify their input and ensure accuracy.

Error Feedback: Provide real-time feedback to users if they make a mistake while entering their password. This could include visual cues such as color changes or error messages indicating an incorrect password.

**Comment by aadeshkulkarni** [comment]
@minhajul-im - Sounds good. Are you picking this up ?

**Comment by minhajul-im** [comment]
okay, but it'll take me time, I am already working on 3 projects. I'll do it!

**Comment by minhajul-im** [comment]
> @minhajul-im - Sounds good. Are you picking this up ?

**Comment by aadeshkulkarni** [comment]
#57 closes this
