### ISSUE TITLE
Refactor | Dockerize the application

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#23]
Docker compose the 2 projects

- frontend 
- backend

**Comment by SandipGyawali** [comment]
@aadeshkulkarni can you assign me this issue i can work with docker

**Comment by aadeshkulkarni** [comment]
Sure, done.

**Comment by SandipGyawali** [comment]
@aadeshkulkarni i have dockerized the frontend section and i have setup the local postgress containered datbase but i am having issue with the backend can you 
help me in the backend setup for the aiven.io and prisma connection pool in wrangler.toml

**Comment by aadeshkulkarni** [comment]
- Aiven.io provides cloud postgres DB (It's connection string resides in .env/DATABASE_URL)
- prisma-accelerate provides connection-pooling (it's connection string resides in wrangler.toml > DATABASE_URL)

If you have containerized postgres DB, the aiven.io part is completed.

The next step would be connection-pooling with prisma.

_My thoughts:_
If we intend to run only 1 instance of the serverless backend on the local machine, disabling connection-pool timeout might work. Offcourse, this is just a workaround.

See if this helps: 
- https://www.prisma.io/docs
- https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool

**Comment by SandipGyawali** [comment]
1. @aadeshkulkarni  y
2. ea the setup is completed i will push the it review it accordingly
