### ISSUE TITLE
Bug | Blogs page | Janky UI for larger content on mobile screens 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#25]
## Where ?
[/blogs](https://medium-app-zeta.vercel.app/blogs)

## What?
On Mobile viewport, when the content height increases, the 'x mins read' text overrides the blog content, making the UI janky.

## Screenshot
<img width="406" alt="Screenshot 2024-05-06 at 8 57 05 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/86ae9974-643b-46a5-9c67-7ebe76c6cf30">

## Expected behaviour:
The content and "x mins read" should not override in any case.

**Comment by KrupaPanchal2527** [comment]
@aadeshkulkarni Could you assign this to me?

**Comment by aadeshkulkarni** [comment]
Sure

**Comment by KrupaPanchal2527** [comment]
Opened a [PR](https://github.com/aadeshkulkarni/medium-app/pull/48) for this. Please review.

**Comment by aadeshkulkarni** [comment]
closed via #48
