### ISSUE TITLE
Bookmark | App shows whitescreen when user bookmarks an article

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#27]
## When ?
- Visit https://medium-app-zeta.vercel.app/
- Click on any blog
- Click on the bookmark icon

## What ?
- An initial whitescreen is shown and then a loader and then the UI is re-painted.

## Expected behaviour
- When user clicks on the bookmark icon, only the bookmark icon should get updated, not the entire page.

## Screenshot

<img width="1792" alt="Screenshot 2024-05-07 at 11 02 59 AM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/3f92853a-0add-42e8-9fc1-bf48c2fdd127">

**Comment by jyo142** [comment]
@aadeshkulkarni please assign to me.

**Comment by aadeshkulkarni** [comment]
@jyo142 - Appbar.tsx  - inside goToBookmarks()

`navigate("/userBookmarks");` should be `navigate("/bookmarks");`
Please incorporate this in your upcoming PR as well.

**Comment by jyo142** [comment]
The main reason that the page is reloading so that we can await the asynchronous change of submitting the bookmark and then retrieve the bookmarkId that is used to delete the bookmark. Is it ok to have the loading icon just in place of the bookmark icon? Having a loading icon while submitting the bookmark will also prevent the user from triggering multiple requests.

**Comment by aadeshkulkarni** [comment]
The page shouldn't reload even if it's waiting for an API response.
Everything on the /blog page is going to remain the same irrespective of the API response. (Except the bookmark icon)

Therefore, It is ok to have the loading icon in place of bookmark icon until the API response is back. 
But the whitescreen shouldn't be visible as it's not a good user experience.

**Comment by aadeshkulkarni** [comment]
@jyo142 - I've refactored blog component. please rebase your branch before working on this so that you wouldn't need to rewrite.
