### ISSUE TITLE
Feature | Show blogs even if user has not signed in.

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#35]
Where ?
- Homepage route "/"

What ?
- On 'Start Reading' button click, redirect user to /blogs (even if user not logged) and show all blog list.
- If user clicks on any specific blog, perform the following action

If user is logged in, then redirect to /blog/:id and show the full blog (Already implemented ✅)
If user is not logged in, then redirect to /signup (Dev needed ❌)

**Comment by KrupaPanchal2527** [comment]
@aadeshkulkarni I have opened a [PR](https://github.com/aadeshkulkarni/medium-app/pull/45) for this.

**Comment by aadeshkulkarni** [comment]
> @aadeshkulkarni I have opened a [PR](https://github.com/aadeshkulkarni/medium-app/pull/45) for this.
> 
> One suggestion, how about we display header on the blogs page when the user is logged in? Currently it doesn't have a header, so it looks a bit weird when a logged in users goes from `/blogs` page to `/blog/{id}` page.

For the sake of UI consistency, let's keep the header visible for authenticated as well unauthenticated routes.
So, let us keep the header for blogs page if the user has / hasn't logged in.

**Comment by aadeshkulkarni** [comment]
#45 closes this
