### ISSUE TITLE
Bug | Login & Signup UI for Mobile

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#37]
The signup and signin pages are janky for smaller mobile screens like iphone 12, 13

### Current UI
<img width="540" alt="Screenshot 2024-05-08 at 8 40 43 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/479da84e-b9e4-41db-b148-4aac12aec6e3">

### Expected UI
There should be sufficient padding on x axis (left and right) of the form fields on mobile viewport.

**Comment by malisettisamrat** [comment]
@aadeshkulkarni Can I work on this issue?
