### ISSUE TITLE
Users should be able to edit their own articles/posts

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#5]
Use React-quill to allow users to edit their articles.

PS: Backend route PUT /api/v1/blog already exists. This is a frontend ticket.

**Comment by jyo142** [comment]
hello @aadeshkulkarni can i help out with this issue?

**Comment by aadeshkulkarni** [comment]
> hello @aadeshkulkarni can i help out with this issue?

Sure, please fork the repository, create a feature branch and raise the pull request
