### ISSUE TITLE
Bug | When user clicks on publish button, no indications that the article is being published

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#50]
### Current:
When a user is writing a new article, on publish button click, the app takes time to publish the article and redirect to the published article. There is no indication (in the form of loader or something else) that the informs the user app is publishing.

### Expectation:
When user clicks the publish button, disable the button & show a loader within the button until the event handler finishes execution. (Consider happy & sad flows)

**Comment by dhairya-create** [comment]
Can you assign me the task?

**Comment by aadeshkulkarni** [comment]
Sure. Please fork the repo, create a branch, and raise a PR. 
Also, link this issue to your PR in the description with appropriate details. (refer existing PRs that are closed)
