### ISSUE TITLE
Enhancement | Sort Articles by Date & claps

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#52]
### Current:
All articles listed in the /blogs page are unsorted and shown in the order they were originally created. That means, the newest article is at the bottom of the page and the oldest article is at the top of the page.

### Expectation:
Articles with highest claps should be at the top AND order by creation-date in descending order (newest at the top)

**Comment by Rohanarora17** [comment]
Can i work on this issue?

**Comment by aadeshkulkarni** [comment]
Sure
