### ISSUE TITLE
Bug | Layout shift when Bookmark button is clicked. 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#58]
### Current:
When an article is opened and the bookmark button is clicked, 
The bookmark icon is replaced with a loader and then replaced by bookmarkIcon again. 
The loader causes a layout shift which is a bad user experience.

### Expectation:
The loader should not cause layout shift

Either eliminate the loader and use a different idea to show loading.
Or
Keep the loader but ensure the dimensions of the loader container and the bookmark container is exactly same so that layout shift is avoided.

**Comment by Hbrehman** [comment]
@aadeshkulkarni - Can I pick this up?

**Comment by aadeshkulkarni** [comment]
Sure, please attach issue links in the PR descriptions. You can create 1 PR for both #51 and this one (since they are related and minor changes)
