### ISSUE TITLE
Feature | User should be able to search articles 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#6]
When user is on the /blogs route, they should be able to search articles using keyword.

Requirement
- Build a backend route GET for search or re-use the existing `/blog/bulk` GET route
- Search component in the frontend with search box & search results.

PS: Searching should be debounced. (Either using lodash or create your own debounced implementation for this)

The search API should be scalable. In future, user should be able to search another user as well.

**Comment by vverma022** [comment]
I'd like to work on this

**Comment by vverma022** [comment]
Cloning the repo locally and working on it

**Comment by aadeshkulkarni** [comment]
Alright. Please fork the repo, create a feature branch, then work on it. 
Raise a PR and link the issue to the PR in description with appropriate screenshots / videos and approach.

**Comment by aadeshkulkarni** [comment]
@vverma022  - Use Medium's search as a reference.

**Comment by aadeshkulkarni** [comment]
@vverma022 - Any update on this ?

**Comment by vverma022** [comment]
> @vverma022 - Any update on this ?

Done with the implementation having issues sending a pull request

**Comment by vverma022** [comment]
![Uploading Screenshot 2024-05-22 at 11.23.25 AM.png…]()

**Comment by aadeshkulkarni** [comment]
The screenshot you uploaded isn't loading. Could you try re-uploading it please ?

**Comment by vverma022** [comment]
<img width="1194" alt="Screenshot 2024-05-22 at 11 23 25 AM" src="https://github.com/aadeshkulkarni/medium-app/assets/109036913/273981fd-fcdc-455b-96ad-0a615381792f">

**Comment by aadeshkulkarni** [comment]
Can you position the search component to the top-left ( on the right of **Medium**) instead of top-right. 

Also, ensure it's mobile responsive.

**Comment by aadeshkulkarni** [comment]
Assign the issue to your PR in the description

**Comment by aadeshkulkarni** [comment]
@vverma022 - Any update on this ? 

[Contributing doc](https://github.com/aadeshkulkarni/medium-app/blob/master/CONTRIBUTING.md)

**Comment by aadeshkulkarni** [comment]
The backend API for Search is now available with this [commit](https://github.com/aadeshkulkarni/medium-app/commit/9b07c0d9a9c237d40a586da71d52c05a699d41b6)

### Update:

GET `/api/v1/blog/search?keyword=[KEYWORD_GOES_HERE]` returns the following response:

```bash
{
post: [{},{}],
users: [{},{}],
tags: [{},{}]
}
```

The frontend needs to make this API call (using debouncing)

**Comment by aadeshkulkarni** [comment]
The frontend changes - [commit](https://github.com/aadeshkulkarni/medium-app/commit/dab3287744bd7e7bb87fccb9d4760f5a5dc583e8)

<hr />

TODO: Mobile Search UI
