### ISSUE TITLE
Style Issue | Improve profile box

### ISSUE THREAD

**Issue by KrupaPanchal2527** [aadeshkulkarni/medium-app#66]
The profile box (top-right corner) doesn't close when clicked outside. Use a popover or menu to render the profile box.

![Medium Blog · 5 39pm · 05-20](https://github.com/aadeshkulkarni/medium-app/assets/54619977/d49b0090-b629-4210-b3c8-7775d55bcf0d)

**Comment by KrupaPanchal2527** [comment]
@aadeshkulkarni Please assign this to me.

**Comment by KrupaPanchal2527** [comment]
@aadeshkulkarni I have added `shadcn` UI library for this purpose. I hope that's fine. If we don't want to bring in any UI library at this point, I can open another PR with a manual fix. 

PR https://github.com/aadeshkulkarni/medium-app/pull/79

**Comment by aadeshkulkarni** [comment]
In two minds regarding `shadcn`. 
If we use it, we might have to refactor some atomic components throughout the frontend.

Having said that, `shadcn` has a lot of cool things and would be useful and we should implement it. 
But, if we integrate it right now, code refactoring might be needed. 

Keeping this as a tech backlog for the near future.

Would be great if you do this without `shadcn`

**Comment by KrupaPanchal2527** [comment]
Okay, I'll do that.

**Comment by KrupaPanchal2527** [comment]
Shall I close the current PR related to this?

**Comment by aadeshkulkarni** [comment]
Yes, please.

**Comment by KrupaPanchal2527** [comment]
Opened a [PR](https://github.com/aadeshkulkarni/medium-app/pull/90) with manual fix.
