### ISSUE TITLE
issue with backend url ??

### ISSUE THREAD

**Issue by Bhavyabhardwaj** [aadeshkulkarni/medium-app#67]
when i replace backend url with my own backend url of cloudflare wokers it give a lot of error while i use your url it works very well ... how is it possible
![Screenshot 2024-05-20 204012](https://github.com/aadeshkulkarni/medium-app/assets/147373271/a9cd9a90-9217-42ff-8adc-ef31939d9f85)

**Comment by aadeshkulkarni** [comment]
That's probably because the db schema migration hasn't happened on your db.

Execute these commands from `backend` directory

`npx prisma generate --no-engine`
`npm install @prisma/extension-accelerate`

Restart the backend server. Should work fine.

Thanks for pointing this out. This was missed in the readme.

**Comment by Bhavyabhardwaj** [comment]
it is still not working don't know why.
is there anything to set in clouflare workers 
![Screenshot 2024-05-21 094359](https://github.com/aadeshkulkarni/medium-app/assets/147373271/2ba34470-54d4-4c68-a429-64238e976e3e)

**Comment by aadeshkulkarni** [comment]
Did you check if the schema is present on your postgres db after db migration ?

You can view your DB using [PgAdmin](https://www.pgadmin.org/download/)

<img width="326" alt="Screenshot 2024-05-21 at 1 56 44 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/d77148f4-d499-417f-98a7-df6dad3cb644">

**Comment by Bhavyabhardwaj** [comment]
yes these are present in my db 
![Screenshot 2024-05-21 163707](https://github.com/aadeshkulkarni/medium-app/assets/147373271/c0722b10-1c4b-44d2-81f1-daebd7aec7fb)

**Comment by Bhavyabhardwaj** [comment]
anyone who is using personal db and cloudflare workers ... this issue comes to yours or not ??

**Comment by aadeshkulkarni** [comment]
What is the error log on your backend console ?

**Comment by Bhavyabhardwaj** [comment]
this 
![image](https://github.com/aadeshkulkarni/medium-app/assets/147373271/f5110614-4c71-4bd4-9b71-20d3e9c16fb1)

**Comment by Bhavyabhardwaj** [comment]
docker commands are also not working don't know what's wrong( i don't know docker very well )

**Comment by Bhavyabhardwaj** [comment]
i think api have to be my backend url it should be workers.dev/v1/blog

**Comment by aadeshkulkarni** [comment]
> this ![image](https://private-user-images.githubusercontent.com/147373271/332403892-f5110614-4c71-4bd4-9b71-20d3e9c16fb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyOTA2NzEsIm5iZiI6MTcxNjI5MDM3MSwicGF0aCI6Ii8xNDczNzMyNzEvMzMyNDAzODkyLWY1MTEwNjE0LTRjNzEtNGJkNC05YjcxLTIwZDNlOWMxNmZiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxMTE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWUyNzRkZGVmMjhiZjg2OWMzZmVmYjdmNDJhNjc5MTA2NmFiNzhmMGQ2N2JiNzkyYWY3MzIwMjllZTJkOTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.npnB54DqMa92_8x0wEf7phzKcZtgv28CWERX-nk4OFs)

This isn't the error log of your backend. It's frontend error log. Check your terminal for backend logs.

**Comment by Bhavyabhardwaj** [comment]
there is no error in my backend

**Comment by Bhavyabhardwaj** [comment]
error in docker compose command 
![image](https://github.com/aadeshkulkarni/medium-app/assets/147373271/87984c24-f822-414c-908a-22d9b1e4456c)

**Comment by aadeshkulkarni** [comment]
> yes ![image](https://private-user-images.githubusercontent.com/147373271/332405952-09684ac8-dca9-465a-b522-e27a9e127b00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMjQwODksIm5iZiI6MTcxNjMyMzc4OSwicGF0aCI6Ii8xNDczNzMyNzEvMzMyNDA1OTUyLTA5Njg0YWM4LWRjYTktNDY1YS1iNTIyLWUyN2E5ZTEyN2IwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQyMDM2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDAyYzZmYjM4NDhhNjc4YTEyYzcwOTJmZDhiZmQ2ZjQ3OGFiOTM3MzI1YmNmY2IyODk0ZjBkNmY5ZjA2NThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xumIYrBD6ixa-yETeqCTEIu1LfPvuCYJPAmTPuJkqFE)

Error code 403 suggests that something is wrong with Auth. Check the Bearer token and also the JWT secret.
