### ISSUE TITLE
Accessibility | Sign In & Sign Up | Enter on last field of the form does not fire event 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#68]
### Where?
- Signup
- Signin

### What?
If user has entered all fields and is on the last field, pressing Enter/Return should execute the button click handler.

**Comment by dhairya-create** [comment]
If you allow I'll look into this bug as well @aadeshkulkarni

**Comment by aadeshkulkarni** [comment]
Sure, assigned to you

**Comment by aadeshkulkarni** [comment]
#75 closes this
