### ISSUE TITLE
Bug | Write page 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#70]
### Current:

Publish button is disabled even if Title & Description is entered

<img width="1796" alt="Screenshot 2024-05-20 at 10 10 40 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/83eb5e7c-c8ff-4661-87c6-af7836a893d0">

### Expected:

Publish button should be enabled once user types Title & Description

**Comment by KrupaPanchal2527** [comment]
Opened a PR for this [here](https://github.com/aadeshkulkarni/medium-app/pull/76). It was a small condition issue, have fixed it now.
