### ISSUE TITLE
Bug | Contributors link | alignment mismatch

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#71]
![Screenshot 2024-05-21 at 2 01 24 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/c9291ca3-6b78-4fd1-a537-bb34d5dc58e2)

### Where ?

In the header

### Expectations:

The Contributors link should be indented as other items in the appbar. (horizontally)

**Comment by KrupaPanchal2527** [comment]
One catch here is that currently `Contributor` link is visible on every page including `Publish` and `Edit blog`. Do we want to keep it as it is or should we only display this link only on root/main page?

@aadeshkulkarni What do you suggest?

**Comment by aadeshkulkarni** [comment]
display only on landing page would be nice.

**Comment by KrupaPanchal2527** [comment]
Opened a [PR](https://github.com/aadeshkulkarni/medium-app/pull/72) with a fix.
