### ISSUE TITLE
Enhancement | Autosave while creating an article

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#77]
### Where ?

`/write` page

### What ?

- When user is writing an article, the app should autosave the changes every 15 seconds onto the local Storage.
- When user redirects to other pages and revisits the write page, they should be able to see the saved content.
- When user logs out and logs in again, visits the write page, they should still be able to see the save content. (until the scope of local storage)
- If user A's article is autosaved, user A logouts. And user B logins on the same window and visits the write page, they should not be able to see the saved content of user A on the screen.

**Comment by KrupaPanchal2527** [comment]
@aadeshkulkarni Could you assign this to me?

**Comment by aadeshkulkarni** [comment]
#114 closes this

> Optmization note: An alternate approach could have been to perform throttling on the title & content onChangeHandlers with a delay of 5-10s.
