### ISSUE TITLE
Feature | Display topic pills on the Blogcard

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#81]
### Current:
The `/blogs` frontend route shows a list of blogcard. Each blogcard looks like this:

![Screenshot 2024-05-22 at 5 12 21 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/336e9a09-d4f6-45fc-9a59-2cd05ca20227)

<hr />

### Expectation:
Show topics / tags for each blogcard in the list.

Something like this:
![Screenshot 2024-05-22 at 5 09 44 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/a3d02ba6-9c74-4d84-bf27-fe22da5841a7)

<hr />

### Points to consider:
- The `/blog/bulk` API endpoint already returns tags for each article like so:

![Screenshot 2024-05-22 at 5 14 15 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/b37c031b-18c2-4dd9-b1fe-819417df010e)

- Show min. 0 and max. any 2 topics ONLY (Even if an article is assigned more than 2 topics)
- Each topic should be a pill (similar to the image shown above)
- Consider responsiveness.

**Comment by JoshuaMartinez1014** [comment]
Hey, I can add the pill with the correct tag from the API. Mind assigning me this and ill get to work on it?

**Comment by aadeshkulkarni** [comment]
Sure

**Comment by swastik4805** [comment]
Does there need to be a single tag per post or all of them?

**Comment by aadeshkulkarni** [comment]
This ticket is for BlogCard component, it should have maximum 2 (due to space constraints)

**Comment by aadeshkulkarni** [comment]
@swastik4805 - The]is issue is assigned to @JoshuaMartinez1014 . 

Please request for the issue before starting development on it to avoid redundancy of work.

**Comment by swastik4805** [comment]
Could you assign the issue to me.....

**Comment by aadeshkulkarni** [comment]
Sure
