### ISSUE TITLE
Feature | Display topics on the Blog page

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#82]
If an article is linked to tags / topics, show all the topics at the end of the article.

<hr />

**Reference:**

![Screenshot 2024-05-22 at 5 19 47 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/8d95ad25-ed8e-4e39-bf7a-31104655cdf1)

<br />

**Pointers:**

The `api/v1/blog` API returns the tags that's linked to the blog.

![Screenshot 2024-05-22 at 5 23 10 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/9577248b-cb91-4d37-8210-d162a9504630)

**Comment by dhairya-create** [comment]
![image](https://github.com/aadeshkulkarni/medium-app/assets/74588712/066893b3-67f0-4e6e-9f4a-f6343204cb48)
Not able to see the field tagsOnPost

**Comment by aadeshkulkarni** [comment]
> ![image](https://private-user-images.githubusercontent.com/74588712/332798881-066893b3-67f0-4e6e-9f4a-f6343204cb48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODk2MzcsIm5iZiI6MTcxNjM4OTMzNywicGF0aCI6Ii83NDU4ODcxMi8zMzI3OTg4ODEtMDY2ODkzYjMtNjdmMC00ZTZlLTlmNGEtZjYzNDMyMDRjYjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE0NDg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MzMxNTZlN2FmNmRmMDJmMDUxMzIwYTA2MWVmMmMxZTFjY2IyNWY5ZGY2NWY2YjYyMGQ2Zjc5MGMzZTIxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._W2shgxjByEvUMSfPJL4Qr3FPNHVor_YSDVtLsrMLLg) Not able to see the field tagsOnPost

Check now. It should be visible. 
Backend code was being deployed when you were checking.

**Comment by dhairya-create** [comment]
Yes, it is visible now.
Kindly assign the task, and I'll look into it.

**Comment by aadeshkulkarni** [comment]
Sure, done.

**Comment by swastik4805** [comment]
Saw the issue and started to fix it. Sorry that i didn't ask to get myself assigned.

**Comment by aadeshkulkarni** [comment]
@swastik4805 - Alright. Next time, please ensure that you get the issue assigned first.
