### ISSUE TITLE
Bug | Deleting your own article

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#85]
### When ? 

- User signs in
- User clicks on an article that's created by themself.
- User clicks on delete button icon.

### What ?

- The backend API returns 411 with the error 'Something went wrong'

### Screenshot: 

<img width="1783" alt="Screenshot 2024-05-23 at 10 33 30 AM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/34962e03-8b2a-45eb-afb8-302bfb19d171">

### Bonus points:

- Ideally, when user clicks on the delete icon, user should be shown confirm dialog before actually deleting the article. A-1 if you can implement it in this ticket. (Optional)

**Comment by dhairya-create** [comment]
A bit new to Node JS, But want to try to solve some of the backend bug as well, Can you assign it?

**Comment by aadeshkulkarni** [comment]
Sure

**Comment by swastik4805** [comment]
I'd be happy to assist with this if @dhairya-create needs any help or isn't able to come up with a solution. Just let me know!

**Comment by dhairya-create** [comment]
Setting up the backend is just going into the backed folder and installing the dependencies right?
Or some extra steps are needed?

**Comment by aadeshkulkarni** [comment]
@dhairya-create - fyi [backend setup](https://github.com/aadeshkulkarni/medium-app?tab=readme-ov-file#backend)

**Comment by aadeshkulkarni** [comment]
#98 closes this
