### ISSUE TITLE
Bug | Profile page - Blogs display

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#86]
### Issue: 

Blogs take up 1/2 of the width

### Expectation:

Blogs should take up the full width of the parent

### Screenshot

<img width="1783" alt="Screenshot 2024-05-23 at 10 39 30 AM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/de236a57-39b7-4ca7-bd3e-87d0cf604dd3">

**Comment by dhairya-create** [comment]
Hey @aadeshkulkarni kindly assign this bug.

**Comment by aadeshkulkarni** [comment]
Done

**Comment by dhairya-create** [comment]
![image](https://github.com/aadeshkulkarni/medium-app/assets/74588712/b1b1e0ee-74dc-4d1e-b930-ceb33647453b)

I guess this would be the output expected

**Comment by aadeshkulkarni** [comment]
Correct, please raise a PR. Thanks
