### ISSUE TITLE
🚀 Super feature | Add Voice over to blog | Text-to-Speech

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#87]
### When ?

- User logs in
- User clicks on a particular blog and it opens up

### What ?

- User can choose to listen to the article instead of just reading it.
- Show an audio toggle icon on the screen that reads the article title, content.

### Where ?

- At the top right of the screen, show the toggle button
- If toggle is on, open a dropdown with voice options
- If toggle is off, voiceover is off.

### References:

- https://github.com/aadeshkulkarni/medium-app/assets/67855887/989e677d-c16c-406b-8bf7-59cee0a4af1b
- https://stackoverflow.com/questions/72422375/text-to-speech-with-javascript

### Note:
- Use external libraries ONLY if it's absolutely necessary and adds visible improvements over manual implementations. (Please discuss in this thread if you're planning to use it)

**Comment by aadeshkulkarni** [comment]
Reference app for benchmarking - https://pi.ai

**Comment by KrupaPanchal2527** [comment]
@aadeshkulkarni This is something new for me. I would love to have a shot at it. Could you please assign to me, if possible?

**Comment by aadeshkulkarni** [comment]
Sure, please share your approach before beginning dev

**Comment by aadeshkulkarni** [comment]
@KrupaPanchal2527 - How's it going ? Any status update ?

**Comment by KrupaPanchal2527** [comment]
@aadeshkulkarni I'll have something by tomorrow.

**Comment by aadeshkulkarni** [comment]
@KrupaPanchal2527 - What is the progress on this one ? Are you facing time crunch or got stuck at a particular problem ?

**Comment by KrupaPanchal2527** [comment]
@aadeshkulkarni Opened a PR for this one - https://github.com/aadeshkulkarni/medium-app/pull/174
