### ISSUE TITLE
Issue | Remove Dark mode TW classes 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#9]
Dark mode is currently not configured and out of project scope at the moment. 
However, there are places where `dark:` Tailwind class is used in certain places.

In Tailwind, the `dark:[class]` is applied automatically if user's default theme in OS is set to dark.

Therefore, Remove all tailwind classes with prefix `dark:` so that all type of users see uniform styling.

Screenshot:
<img width="390" alt="Screenshot 2024-04-27 at 7 56 44 AM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/0266720d-f0ee-4799-9448-7765bfb5078d">

**Comment by syrok94** [comment]
hey, can I work on this issue?

**Comment by rahul-mahato29** [comment]
Hey @aadeshkulkarni , here's the PR - #12
