### ISSUE TITLE
Feature | Filter Topics on Blogs page

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#92]
### Where ? 
- https://medium-app-zeta.vercel.app/blogs

### What ?
- Show a list of all topics horizontally like this.

<img width="861" alt="Screenshot 2024-05-24 at 9 59 42 AM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/96bc3706-2ff0-4cb5-8387-b61dfb05f5f8">

### Backend routes:

- The GET `/api/v1/tag` API endpoint returns a list of all topics which can be used to show all topics
- The GET `api/v1/blog/bulk?tagId=[TAG_ID]` API endpoint returns a list of blogs for the topic with specific TAG_ID

### Objective:
1. Show all topics / tags
2. Filter the blogs if user clicks on any topic / tag.

PS: Reuse existing components wherever possible.

**Comment by dhairya-create** [comment]
Can I pick up this issue?

**Comment by aadeshkulkarni** [comment]
Sure

**Comment by dhairya-create** [comment]
This horizontal bar should be embedded in Header?
Or should it be after the Header?

**Comment by aadeshkulkarni** [comment]
> This horizontal bar should be embedded in Header? Or should it be after the Header?

It should be embedded after the Header. It should also be a component that can be reused in other parts of the apps in future.

**Comment by dhairya-create** [comment]
![image](https://github.com/aadeshkulkarni/medium-app/assets/74588712/0b99592e-cf95-4110-a2ff-bc6846a67b86)


-> Created a topic Slider which is currently rendering all the topic tags


Doubt:
->Should I make custom hooks for both endpoint routes as I cannot see the custom hooks for these 2 routes?
-> Making custom hooks will avoid redundant code of calling the API in the future if we have to call APIs in multiple parts of the application

**Comment by aadeshkulkarni** [comment]
> ![image](https://private-user-images.githubusercontent.com/74588712/336168475-0b99592e-cf95-4110-a2ff-bc6846a67b86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0Mzg4OTEsIm5iZiI6MTcxNzQzODU5MSwicGF0aCI6Ii83NDU4ODcxMi8zMzYxNjg0NzUtMGI5OTU5MmUtY2Y5NS00MTEwLWEyZmYtYmM2ODQ2YTY3Yjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE4MTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMDgyOGFhZWVkNjdiM2NmZjkyYTdjODUzMGFhNGU4NmM1YjlhOWIzZjNjNDZiYmY3YjUxYjI3YzE4ZjhjYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tywe_Lz-S4T0bObvox9FsCE9NyvezKrJJ9Uh3MWuEDg)
> 
> -> Created a topic Slider which is currently rendering all the topic tags
> 
> Doubt: ->Should I make custom hooks for both endpoint routes as I cannot see the custom hooks for these 2 routes? -> Making custom hooks will avoid redundant code of calling the API in the future if we have to call APIs in multiple parts of the application

1. Absolutely yes.
2. Absolutely yes.

Can you make the UI look like this ? This will look much more cleaner.

<img width="843" alt="Screenshot 2024-06-03 at 11 48 15 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/27440af9-71b6-4404-a6b9-ef7bb7e62a6f">

**Comment by dhairya-create** [comment]
Okay I'll replicate this UI

**Comment by aadeshkulkarni** [comment]
@dhairya-create  - Any status update on this issue ? It's been a long time.

**Comment by dhairya-create** [comment]
Sorry for the delay, was down with fever
I will close this issue by tomorrow

**Comment by dhairya-create** [comment]
I want to pass queryString in useBlogs, but I need to change the whole logic of useBlogs.
Would you happen to have any approach on how to pass it?

**Comment by aadeshkulkarni** [comment]
> I want to pass queryString in useBlogs, but I need to change the whole logic of useBlogs. Would you happen to have any approach on how to pass it?

Please elaborate. 
Fetching queryString within useBlogs is a fairly straight forward approach using `useSearchParams`.
